<?php
/**
 * Steadfast COD amount — keep it honest.
 *
 * This store's COD gateway (assurance-cod-bkash, see inc/checkout.php +
 * the plugin of the same name) is a hybrid: the courier charge is
 * collected up front via bKash, and only the book price is due at the
 * door. Neither WooCommerce core nor the third-party Steadfast API plugin
 * know about that split:
 *
 *   - WooCommerce's admin "Paid" row always shows the full order total
 *     once payment_complete() has run — correct for a normal gateway, but
 *     read literally here it implies nothing is owed at the door.
 *   - The Steadfast plugin's COD amount (both on the printed invoice and,
 *     more importantly, in the parcel actually booked with the courier)
 *     defaults to the full order total whenever staff haven't typed an
 *     override into its "amount" column — which double-charges the
 *     customer for delivery on every hybrid order left at its default.
 *
 * Both are fixed here without touching WooCommerce core or a single line
 * of the vendor Steadfast plugin, so nothing here is at risk from a
 * plugin/core update — this file is the entire fix:
 *
 *   - assurance_backfill_steadfast_amount() writes the correct number into
 *     the Steadfast plugin's own `steadfast_amount` post meta, which the
 *     plugin already treats as the authoritative COD amount for both the
 *     invoice and the API call — so giving it the right default fixes both
 *     from the outside, with no plugin edit. It re-syncs that value every
 *     time this runs, as long as the field still holds exactly what this
 *     function last put there itself — the moment a human types a
 *     different number in, that's treated as a deliberate override and
 *     left alone. (An earlier version only ever filled an *empty* value —
 *     but the Steadfast plugin itself defaults the field to "0", not "",
 *     so that version could get permanently stuck at 0 the first time it
 *     ran before an order had any items yet. See the function for detail.)
 *   - assurance_admin_due_at_delivery_row() adds a plain "Due at delivery"
 *     line under the order totals, and visually corrects the "Paid" row
 *     next to it to show the courier fee actually collected via bKash
 *     (rather than the full order total WooCommerce prints there) — both
 *     only once the courier-fee prepayment has actually gone through
 *     (order Processing/Completed/Refunded with a payment date), not on a
 *     still-Pending order where nothing has been collected yet.
 *   - assurance_pdf_invoice_due_row() does the same "Due at Delivery" row
 *     on the customer-facing PDF invoice generated by the "Print Invoices
 *     & Packing Slips for WooCommerce" (WebToffee) plugin — again via a
 *     filter it already exposes (wt_pklist_alter_order_template_html), not
 *     a template override, so it survives that plugin's updates too.
 *
 * @package Assurance
 */

defined( 'ABSPATH' ) || exit;

/**
 * What the courier should actually collect at the door for this order.
 *
 * @param WC_Order $order Order.
 * @return float
 */
function assurance_cod_amount_due( $order ) {
	if ( 'assurance_cod' !== $order->get_payment_method() ) {
		// Any other gateway (bKash full payment, etc.) collects everything
		// online — nothing left for the courier to collect.
		return 0.0;
	}

	$fee = (float) $order->get_meta( '_assurance_cod_courier_fee' );

	return max( 0.0, (float) $order->get_total() - $fee );
}

/**
 * Whether the COD order's courier-fee prepayment has actually gone
 * through yet — the same condition WooCommerce's own "Paid" row uses
 * (see html-order-items.php in WooCommerce core), so "Due at Delivery"
 * and the Paid-row correction only ever appear once there's really
 * something to show, not on a still-Pending manual order where nothing
 * has been collected.
 *
 * @param WC_Order $order Order.
 * @return bool
 */
function assurance_cod_courier_fee_paid( $order ) {
	return in_array( $order->get_status(), array( 'processing', 'completed', 'refunded' ), true )
		&& $order->get_date_paid();
}

/**
 * Pre-fill (and keep in sync) the Steadfast plugin's own amount field with
 * the real due-at-delivery figure, unless staff have typed a deliberate
 * override in.
 *
 * Nothing here edits the vendor plugin — it already treats the
 * `steadfast_amount` post meta as the authoritative COD figure for both
 * the printed invoice and the actual parcel booked with the courier, so
 * writing the correct number into that same meta is enough to fix both,
 * and it survives a Steadfast plugin update untouched.
 *
 * @param int $order_id Order ID.
 */
function assurance_backfill_steadfast_amount( $order_id ) {
	$order = wc_get_order( $order_id );

	if ( ! $order || 'assurance_cod' !== $order->get_payment_method() ) {
		return;
	}

	$due       = assurance_cod_amount_due( $order );
	$current   = get_post_meta( $order_id, 'steadfast_amount', true );
	$last_auto = get_post_meta( $order_id, '_assurance_steadfast_amount_auto_value', true );

	$still_ours  = '' !== $last_auto && (string) $current === (string) $last_auto;
	$legacy_zero = '' === $last_auto && '0' === (string) $current;

	if ( '' !== $current && ! $still_ours && ! $legacy_zero ) {
		return; // Diverged from what we last wrote (or predates tracking, and isn't the legacy-bug "0") — a human's deliberate override.
	}

	if ( (string) $due !== (string) $current ) {
		update_post_meta( $order_id, 'steadfast_amount', $due );
	}

	update_post_meta( $order_id, '_assurance_steadfast_amount_auto_value', (string) $due );
}

/*
 * Three independent triggers, so the figure is right well before anyone
 * can act on it — no single one of these is relied on alone:
 *
 *   - payment_complete: the normal case, fires the moment bKash confirms
 *     the courier fee (or immediately for free-shipping COD).
 *   - order_status_changed: catches an order pushed to Processing by hand,
 *     or any flow that skips payment_complete().
 *   - the admin order screen itself: a last-resort self-heal for orders
 *     placed before this fix existed, or anything the two hooks above
 *     somehow missed — it runs the instant staff open the order, which is
 *     always before they can click "Send" to Steadfast.
 */
add_action( 'woocommerce_payment_complete', 'assurance_backfill_steadfast_amount' );
add_action( 'woocommerce_order_status_changed', 'assurance_backfill_steadfast_amount' );
add_action( 'woocommerce_admin_order_data_after_order_details', function ( $order ) {
	assurance_backfill_steadfast_amount( $order->get_id() );
} );

/**
 * Surface the real due-at-delivery amount on the admin order screen, and
 * visually correct the "Paid" row next to it.
 *
 * WooCommerce's core "Paid" row (get_total()) is core behaviour shared by
 * every COD-style gateway and isn't itself wrong at the data level —
 * "paid" there means "this gateway's flow completed", not "cash in hand" —
 * but read literally on a hybrid order it's actively misleading (it says
 * the full order total was collected, when only the courier fee was), and
 * there's no filter hook around that specific price in WooCommerce core's
 * template (includes/admin/meta-boxes/views/html-order-items.php prints it
 * with a bare wc_price() call). So the amount itself is corrected here
 * with a small inline script instead — display-only, runs after the "Paid"
 * row already exists in the page, and never touches $order->get_total()
 * or anything persisted, so reports/exports/order emails are unaffected.
 *
 * @param int $order_id Order ID.
 */
function assurance_admin_due_at_delivery_row( $order_id ) {
	$order = wc_get_order( $order_id );

	if ( ! $order || 'assurance_cod' !== $order->get_payment_method() ) {
		return;
	}

	if ( ! assurance_cod_courier_fee_paid( $order ) ) {
		return; // Courier fee hasn't actually been collected yet — nothing to correct or show.
	}

	$fee = (float) $order->get_meta( '_assurance_cod_courier_fee' );

	if ( $fee <= 0 ) {
		return; // Free-delivery COD order — nothing was prepaid, so the full total already is the due amount.
	}

	?>
	<tr>
		<td class="label label-highlight"><?php esc_html_e( 'Due at Delivery', 'assurance' ); ?>:</td>
		<td width="1%"></td>
		<td class="total">
			<?php echo wp_kses_post( wc_price( assurance_cod_amount_due( $order ), array( 'currency' => $order->get_currency() ) ) ); ?>
		</td>
	</tr>
	<tr>
		<td colspan="3" style="display:none">
			<script>
			( function () {
				var rows = document.querySelectorAll( '.wc-order-totals tr' );
				for ( var i = 0; i < rows.length; i++ ) {
					var label = rows[ i ].querySelector( 'td.label' );
					if ( ! label || label.textContent.trim().indexOf( <?php echo wp_json_encode( __( 'Paid', 'woocommerce' ) ); ?> ) !== 0 ) {
						continue;
					}
					var total = rows[ i ].querySelector( 'td.total' );
					if ( total ) {
						total.innerHTML = <?php echo wp_json_encode( wc_price( $fee, array( 'currency' => $order->get_currency() ) ) ); ?>;
					}
					break;
				}
			} )();
			</script>
		</td>
	</tr>
	<?php
}
add_action( 'woocommerce_admin_order_totals_after_total', 'assurance_admin_due_at_delivery_row' );

/**
 * Add the same "Due at Delivery" row to the customer-facing PDF invoice.
 *
 * Hooks wt_pklist_alter_order_template_html, which the WebToffee plugin
 * runs the raw template HTML through before it fills in any of the
 * `[wfte_...]` value placeholders (see generate_template_html() in the
 * plugin's customizer.php) — so $order is already the real order object,
 * but the row this inserts is built with an already-resolved price
 * string rather than a new placeholder token, since the token/find-replace
 * pipeline is plugin-internal and not something worth reverse-engineering
 * from the theme. Inserting straight after the existing Total row keeps it
 * reading like a natural part of the template rather than a bolt-on.
 *
 * @param string   $html          Template HTML.
 * @param string   $template_type Which document is being built ('invoice', 'packing-list', ...).
 * @param WC_Order $order         Order.
 * @return string
 */
function assurance_pdf_invoice_due_row( $html, $template_type, $order ) {
	if ( 'invoice' !== $template_type || ! $order instanceof WC_Order ) {
		return $html;
	}

	if ( 'assurance_cod' !== $order->get_payment_method() ) {
		return $html;
	}

	if ( ! assurance_cod_courier_fee_paid( $order ) ) {
		return $html; // Courier fee hasn't actually been collected yet.
	}

	$fee = (float) $order->get_meta( '_assurance_cod_courier_fee' );

	if ( $fee <= 0 ) {
		return $html; // Free-delivery COD order — the Total row already is the due amount.
	}

	// Match the plugin's own price formatting (currency symbol, decimals,
	// position) instead of wc_price(), so the new row looks identical to
	// the rows already on the invoice rather than subtly different.
	if ( ! class_exists( 'Wf_Woocommerce_Packing_List_Admin' ) || ! class_exists( 'Wt_Pklist_Common' ) ) {
		return $html;
	}

	$user_currency = Wt_Pklist_Common::get_order_meta( $order->get_id(), 'currency', true );
	$due_formatted = Wf_Woocommerce_Packing_List_Admin::wf_display_price( $user_currency, $order, assurance_cod_amount_due( $order ) );

	$row = '<tr class="wfte_payment_summary_table_row wfte_product_table_payment_total assurance_due_row">'
		. '<td class="wfte_left_column"></td>'
		. '<td class="wfte_product_table_payment_total_label wfte_text_right">' . esc_html__( 'Due at Delivery', 'assurance' ) . '</td>'
		. '<td class="wfte_product_table_payment_total_val wfte_right_column wfte_text_left">' . wp_kses_post( $due_formatted ) . '</td>'
		. '</tr>';

	// Insert right after the existing Total <tr>...</tr>, so it reads
	// directly under the number the customer already looked at. Matched as
	// an actual <tr> tag (not just the class name as a substring) because
	// "wfte_product_table_payment_total" also appears earlier in the
	// template's own <style> block as a CSS selector — a plain strpos()
	// on the class name would have latched onto that instead and inserted
	// this row right after the table header.
	$matched = preg_match(
		'/<tr\b[^>]*\bwfte_product_table_payment_total\b[^>]*>.*?<\/tr>/is',
		$html,
		$row_match,
		PREG_OFFSET_CAPTURE
	);

	if ( ! $matched ) {
		return $html;
	}

	$insert_at = $row_match[0][1] + strlen( $row_match[0][0] );

	return substr( $html, 0, $insert_at ) . $row . substr( $html, $insert_at );
}
add_filter( 'wt_pklist_alter_order_template_html', 'assurance_pdf_invoice_due_row', 20, 3 );
